In [1]:
import pandas as pd

imported Pandas as pd so that I can work on a table in python.

In [2]:
cols =["CRIM","ZN","INDUS","CHAS","NOX","RM", "AGE","DIS","RAD","TAX", "PTRATIO","B","LSTAT","MEDV"]
df= pd.read_csv("4__house_Prediction_Data_Set.csv", sep=r"\s+", header=None, names=cols)

I label each of the 14 columns

In [3]:
df.shape

(506, 14)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [5]:
df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

It checks if there are empty cells

In [6]:
df.duplicated().sum()

np.int64(0)

It shows that there are no duplicated cells

In [7]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [8]:
X=df.drop(["MEDV","B"], axis=1)

I dropped MEDV because that what is to be will be predicted after going through all the data in each column

In [9]:
y=df["MEDV"]
X.shape

(506, 12)

made my lowercase y what will be predicted after all the column has been read

In [10]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train,y_test=train_test_split(
    X,y, test_size =0.2, random_state=42

)
print(X_train.shape , X_test.shape)

(404, 12) (102, 12)

I tested and trained the dataset. I split 9the dataset, The test set was 20% of the main dataset and the train dataset was 80% and I also malde my random state 42

In [11]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit (X_train,y_train)

LinearRegression()

Imported linearRegression from scikit learn, made the model a LinearRegression and also made sure I fit just the train dataset so has to avoid data leakage

In [12]:
model.intercept_

np.float64(36.97046906703031)

In [13]:
pd.Series(model.coef_, index=X.columns)

CRIM       -0.127196
ZN          0.030795
INDUS       0.025248
CHAS        3.049477
NOX       -18.183246
RM          4.240098
AGE        -0.003594
DIS        -1.465507
RAD         0.239990
TAX        -0.011275
PTRATIO    -0.894845
LSTAT      -0.537770
dtype: float64

In [14]:
from sklearn.metrics import r2_score, mean_squared_error

In [15]:
y_pred = model.predict(X_test)
r2_score(y_test,y_pred)

0.6893967884614753

Imported r2_score and mean_squared_error
I calculated the r2 score as specified in the objective

In [16]:
mean_squared_error(y_test, y_pred)

22.77770856386609

Calculated the MSE as specified In the objective

In [17]:
mean_squared_error(y_test, y_pred) ** 0.5

4.772599769922687