**Task 3: KNN Classifier on Iris Dataset**

In [1]:
import pandas as pd

Imported pandas so I will be able to work with table in python

In [2]:
df= pd.read_csv("1__iris.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

read the uploaded documents and I viewed the first 5 rows

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

asked for more information on the dataframe.
It shows I have 150 entries

In [4]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

checked through the dataframe if there is  null input and sums it up.It shows that there is no empty input.

In [5]:
df.duplicated().sum()

np.int64(3)

checks if there are duplicates. There are 3 duplicated rows

In [6]:
df=df.drop_duplicates()

dropped all the duplicated rows so as not to cause confusion

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 147 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  147 non-null    float64
 1   sepal_width   147 non-null    float64
 2   petal_length  147 non-null    float64
 3   petal_width   147 non-null    float64
 4   species       147 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.9+ KB

Checked the infomation for the dataframe.
with this I have successfully loaded and preprocessed the data frame.

In [8]:
X = df.drop("species", axis=1)
y = df["species"]

X is the input of each rows
y is the target (what we want to find out after knowing all the input is X)
species were left as text because it makes the reports easy to read

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

imported train_test_split from scikit learn and split my X and y into train and test .
20% of the whole data frame was my test data and I made my random state to be 42 so that it is repeatable
and I stratify y so that there will be an even distrubution of all the species.

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled =scaler.fit_transform(X_train)
X_test_scaled =scaler.transform(X_test)

Okay so here I imported StandardScaler from scikit learn so as to treat the numbers the same way so no column dominates by size alone.
I fit_ transform the X_train. it studies trainind data and works out each column's average and spread and I use numbers to rescale the columns.
and for the X_test I don,t study it(fit) and just rescale it(transform).

In [11]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors= 5)
knn.fit( X_train_scaled,y_train)
y_pred=knn.predict(X_test_scaled)

imports a KNN tool from scikit learn's "neighbors"
Creates an empty KNN model and stores it under the name knn
n_neighbors = 5 sets k to 5, so that 5 most similar flowers vote
.fit() takes the input first and the answer second.fitting mostly means storing the training data.
and also I asjed the model to classify each rows of the held-back test inputs and store the predictions in y_pred

With this I have successfully built a KNN classifier.

In [12]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [13]:
accuracy_score(y_test, y_pred)

0.9333333333333333

Evaluated the accuracy
compares the real species (y_test) with the model's guesses (y_pred), it returns 0.933 which means 93.3%

In [14]:
confusion_matrix(y_test,y_pred)

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  2,  8]])

 Rows are the real species and columns are the guesses in alphabetical order(setosa, versicolor ,virginica)
 The first row there were  real setosa and 10 were guessed correctly
 The same goes for the second row
 But the third row  there were 10 real virginica but only 8 were guessed correctly the remaining 2 was guessed wrong(it was guessed to be under versicolor)

In [15]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.83      1.00      0.91        10
   virginica       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30

prints a table with precision(when the model said this species ,how often was it right?) and recall(of all the real ones, how many did it find ?)
The precision for setosa and virginica were 1.0 that mean the prediction for all were right while The precision for versicolor was 0.83 that means instead of 10 times the model predicted 12 times

The recall for setosa and versicolor were 1.0 which means it found all. while virginica recall 0.80 because it only found 8 out of 10

In [16]:
# Comparing the different values of K
for k in [1, 3, 5, 7, 9, 11]:
  model_k = KNeighborsClassifier(n_neighbors=k)
  model_k.fit(X_train_scaled,y_train)
  y_pred_k = model_k.predict(X_test_scaled)
  print(k,accuracy_score(y_test,y_pred_k))

1 0.9666666666666667
3 0.9333333333333333
5 0.9333333333333333
7 0.9666666666666667
9 0.9666666666666667
11 0.9666666666666667

Created a  for loop that compared the accuracy of k when it is 1,3,5,7,9,11
0.9667 means 29 out of 30  flowers were predicted correctly
0.9333 mears 28 out of 30 flowers were predicted correctly

k=1,7,9, and 11 gave the highest accuracy,but the difference between the values is only one flower out of 30

I would choose K = 7 or 9 or 11 it ties for the highest accuracy and its asks several neighbours instead of 1. which is the reasin I did not choose k=1 even though it also had high accuracy.

**IN CONCULSION**
Setosa never got confused with any of the other species because its measurement was clearly different from the other two species.
while Versicolor and Virginica overlapped